### ISSUE TITLE
Custom Fields for ArcLab Discover post editor not found

### ISSUE THREAD

**Issue by jame5chia** [arclab-io/ALwordpressGridPlus#4]
I'm trying to add a new ArcLab Discover template.

Following the [User Guide](https://www.notion.so/arclab-io/Discover-WordPress-Module-Management-35bcfb85870f476eafbe925fc2a111d8), I'm looking for the Custom Fields to add the 3 variables: https://www.notion.so/arclab-io/Discover-WordPress-Module-Management-35bcfb85870f476eafbe925fc2a111d8?pvs=4#5878f3e0b311433baf6e286b774b1939

However, I can't find them in the Custom Field dropdown
![image](https://user-images.githubusercontent.com/65056541/223298876-c88e8579-75a8-46db-8485-54a3900fd008.png)

My current ArcLab Discover draft post here: https://arclab.io/wp-admin/post.php?post=24019&action=edit

**Comment by nioq** [comment]
I'm not 100% sure as (I'm ashamed to say) I've not actually gone through the steps before myself, but I believe you might just need to click on "Enter new" and type in the values yourself?

![image](https://github.com/arclab-io/ALwordpressGridPlus/assets/869072/1425cb4a-b227-43d1-b2d3-a82427a20c5e)

**Comment by jame5chia** [comment]
https://tinkertanker.slack.com/archives/C01QL2BCV4L/p1690862334634619?thread_ts=1689918057.513649&cid=C01QL2BCV4L
